### ISSUE TITLE
Not compatibility with redmine 3.3.x

### ISSUE THREAD

**Issue by liomoura** [nanego/redmine_per_tracker_categories#1]

**Comment by nanego** [comment]
You will have to detail your issue/bug, because I'm currently using this plugin in production with Redmine 3.3.0, without any issue...

**Comment by poxtihc** [comment]
Not working with 3.3.0.
After installing, I do not see any effect on Issue Categories screen

![imagen](https://cloud.githubusercontent.com/assets/7653000/22097570/0a55b066-de22-11e6-8627-1e9e6742e70f.png)

Regards

**Comment by nanego** [comment]
I confirm you should see a tracker field in this page. Did you restart your server? Any error in logs?

**Comment by poxtihc** [comment]
Yes, migrate+restart without error.

When adding a new category,  no errors either
```
Started GET "/projects/test/issue_categories/new" for 172.22.41.102 at 2017-01-19 09:59:54 +0100
Processing by IssueCategoriesController#new as HTML
  Parameters: {"project_id"=>"test"}
  Current user: admin (id=1)
  Rendered issue_categories/_form.html.erb (6.7ms)
  Rendered issue_categories/new.html.erb within layouts/base (9.3ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (1.4ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (2.2ms)
  Rendered plugins/sidebar_hide/app/views/sidebar/_hideButton_partial.html.erb (0.7ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_body_bottom.html.erb (0.7ms)
  Rendered plugins/time_logger/app/views/time_loggers/_embed_menu.html.erb (17.1ms)
  Rendered plugins/time_logger/app/views/time_loggers/_update_menu.html.erb (18.2ms)
Completed 200 OK in 95ms (Views: 74.7ms | ActiveRecord: 7.3ms)
```

**Comment by nanego** [comment]
Actually, I think this bug is not related to the Redmine version.
You probably did not install the required redmine_deface_plugin. I have updated the Readme file.

**Comment by poxtihc** [comment]
It works with redmine_base_deface plugin.

For easyredmine users or redmine_tweaks, deface gem version should be >= 1.1.0
 I suggest to update Gemfile

`gem 'deface' , (">= 1.1.0")`

Regards
