### ISSUE TITLE
Last commit broke compatibility with Rails 3

### ISSUE THREAD

**Issue by slabstone** [nanego/redmine_per_tracker_categories#3]
Tried installing on Redmine 3.3.1, Ruby 2.3.3, Rails 4.2.7.1, got an error `NameError: uninitialized constant ActiveSupport::Reloader`, reverting 67c934d3ee27ae819af8f98567fd045be50c81b2 helped.

**Comment by nanego** [comment]
Yes, the latest version is only compatible with Redmine 4.

**Comment by slabstone** [comment]
Can you update `README.md` then, please? It says "This plugin has been tested with Redmine 3.3+."

**Comment by nanego** [comment]
I have just updated the Readme file. Thank you.
